environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: ""

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Set global username and email
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  # run tests
  - npm test -- -t 20000

# Don't actually build.
build: off
